#!/bin/bash
cd Projet_PROG5
FILES=$(find ./Examples_loader -name "example?.o")

#Color
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

for file in $FILES
do

readelf -h $file > output_readelf1
./readelf2 -h $file > output_readelf2

echo -e "${BLUE}START TEST ON ${YELLOW} $file ${NC}:"


res=1


while read lineFile1 <&3 && read lineFile2 <&4  
do  
    lineTest1=$(echo $lineFile1 | cut -f1 -d':')
    lineTest2=$(echo $lineFile2 | cut -f1 -d':')

    if [ "$lineTest1" == 'Données' ] && [ "$lineTest1" == "$lineTest2" ]
    then
        line1=$(echo $lineFile1 | cut -f2 -d':' | tr -d " \t\n\r")
        line2=$(echo $lineFile2 | cut -f2 -d':' | tr -d " \t\n\r")
    elif [ "$lineTest1" == 'Fanions' ] && [ "$lineTest1" == "$lineTest2" ] 
    then
        line1=$(echo $lineFile1 | cut -f2 -d':' | cut -f1 -d',' | tr -d " \t\n\r")
        line2=$(echo $lineFile2 | cut -f2 -d':' | cut -f1 -d',' | tr -d " \t\n\r")
    else
        line1=$(echo $lineFile1 | cut -f2 -d':' | cut -f1 -d'(' | tr -d " \t\n\r")
        line2=$(echo $lineFile2 | cut -f2 -d':' | cut -f1 -d'(' | tr -d " \t\n\r")
    fi

    if [ "$line1" != "$line2" ] ; then
        lineEcho1=$(echo $lineFile1 | tr -d "\t\n\r")
        lineEcho2=$(echo $lineFile2 | tr -d "\t\n\r")
        echo -e "\"$lineEcho1\" ${PURPLE}DIFFERENT THAN${NC} \"$lineEcho2\""
        res=0
    fi 
    
done 3<output_readelf1 4<output_readelf2

if [ $res == 0 ] ; then
    echo -e "${RED}ERROR (see above)${NC}\n"
else
    echo -e "${GREEN}SUCCESS${NC}\n"
fi


done

rm output_readelf1
rm output_readelf2
